// <auto-generated />
using System;
using Consumer.Infastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consumer.Migrations.Migrations
{
    [DbContext(typeof(ConsumerDbContext))]
    partial class ConsumerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consumer.Domain.Aggregates.OrganizationAggregate.Organization", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.ToTable("Organizations", "consumer");
                });

            modelBuilder.Entity("Consumer.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("_organizationGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OrganizationGuid");

                    b.HasKey("Guid");

                    b.HasIndex("_organizationGuid");

                    b.ToTable("Users", "consumer");
                });

            modelBuilder.Entity("Consumer.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.HasOne("Consumer.Domain.Aggregates.OrganizationAggregate.Organization", null)
                        .WithMany("Users")
                        .HasForeignKey("_organizationGuid")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Consumer.Domain.Aggregates.OrganizationAggregate.Organization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
